name: tiled
adopt-info: tiled
version: git
license: GPL-2.0
base: core20

grade: stable
confinement: strict

apps:
  tiled:
    command-chain: &command-chain
      - bin/desktop-launch
    command: usr/bin/tiled
    common-id: org.mapeditor.Tiled.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - removable-media
      - opengl
      - network
  tmxviewer:
    command-chain: *command-chain
    command: usr/bin/tmxviewer
    plugs: &basic-plugs
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - home
      - removable-media
  tmxrasterizer:
    command-chain: *command-chain
    command: usr/bin/tmxrasterizer
    plugs: *basic-plugs
  terraingenerator:
    command-chain: *command-chain
    command: usr/bin/terraingenerator
    plugs: *basic-plugs

parts:
  tiled:
    plugin: qmake
    qmake-parameters:
      - PREFIX=/usr
      - SYSTEM_ZSTD=yes
      - CONFIG+=release
    parse-info:
      - usr/share/metainfo/org.mapeditor.Tiled.appdata.xml
    source: .
    build-packages:
      - pkg-config
    # FIXME: Python plugin compiles and loads, but can't find platform libraries
    #  - python-dev
      - qttools5-dev-tools
      - qtdeclarative5-dev
      - zlib1g-dev
      - libzstd-dev
    stage-packages:
      - libqt5quick5
    #  - libpython2.7
      - libzstd1
    after: [desktop-qt5]

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
